controller_frequency: 3.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false
recovery_behaviors: [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}, {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]

TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.3
  max_vel_theta: 0.4
  min_vel_theta: -0.4
  min_in_place_vel_theta: 0.4
  max_rotational_vel: 0.4
  min_in_place_rotational_vel: 0.4
  escape_vel: -0.10
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_theta: 0.05

  holonomic_robot: false
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.20
  gdist_scale: 2.0
  pdist_scale: 2.0

  heading_lookahead: 1.5
  heading_scoring: true
  heading_scoring_timestep: 0.5
  meter_scoring: false
  oscillation_reset_dist: 0.05
  occdist_scale: 0.05
  publish_cost_grid_pc: false

  sim_time: 1.7
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 8
  vtheta_samples: 20
  dwa: false
  simple_attractor: false
  
