plugins:
  - {name: static_layer, type: 'costmap_2d::StaticLayer'}
  - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
  - {name: sonar,   type: "range_sensor_layer::RangeSensorLayer"}

inflation_layer:
    robot_radius: 0.2
    inflation_radius: 0.2

sonar:
    topics: ['/sonar_data']

obstacle_layer:
    combination_method: 1
    enabled: true
    footprint_clearing_enabled: true
    max_obstacle_height: 0.6
    observation_sources: scan
    obstacle_range: 2.5
    raytrace_range: 3.0
    scan: {clearing: true, data_type: LaserScan, expected_update_rate: 0, marking: true,
      topic: /scan_filtered}
